name: Joomla Component Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Validate manifest file
      run: |
        if [ ! -f administrator/components/com_brostravel/brostravel.php ]; then
          echo "brostravel.php not found"
          exit 1
        fi
        if [ ! -f administrator/components/com_brostravel/com_brostravel.xml ]; then
          echo "com_brostravel.xml not found"
          exit 1
        fi

    - name: Zip component
      run: zip -r com_brostravel.zip administrator components

    - name: Upload component zip
      uses: actions/upload-artifact@v3
      with:
        name: com_brostravel
        path: com_brostravel.zip
